# Usa una imagen base oficial de Node.js (puede ser alpine para que sea más ligera)
FROM node:20-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias para usar cache de Docker
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Si usas Typescript, compila el proyecto
RUN npm run build

ENV PORT 8080
ENV HOST 0.0.0.0
# Exponer el puerto que usará la app (usualmente 3000 o el que definas)
EXPOSE 8080


# Comando para iniciar la app ya compilada
CMD ["npm","run","start:prod"]
