name: Build and Push Docker API to Artifact Registry

on:
  push:
    branches:
      - migration_databases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 🔐 Autenticación recomendada con auth@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 🐳 Configura Docker para Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -f Dockerfile-api -t us-docker.pkg.dev/chivosmart-app/chivosmart-api-repo/chivo-smart-api:$GITHUB_SHA .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-docker.pkg.dev/chivosmart-app/chivosmart-api-repo/chivo-smart-api:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy chivo-smart-api \
          --image=us-docker.pkg.dev/chivosmart-app/chivosmart-api-repo/chivo-smart-api:${{ github.sha }} \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
